### ISSUE TITLE
Another bug I have noticed

### ISSUE THREAD

**Issue by Richard38907** [Arturo254/InnerTune#10]
I tested this fork on my OnePlus 10t 5g and it works really fine. Now I test it on my OnePlus Nord Avicii (2020) and the UI/scrolling lags a bit compared to the original 0.5.3 version. Is it normal?

**Comment by Arturo254** [comment]
I'll try to create a version for your One plus Nord Avicii 
And check the logacat to see and fix the problem

**Comment by Richard38907** [comment]
I'm on PixelExperience 13 ROM. Unfortunately, the bug report feature present in developer options is unavailable on this ROM.

**Comment by Richard38907** [comment]
Oops I didn't noticed that my battery level was very low, charged now and the problem seems to be solved😅😅. Issue closed✅. Sorry.

**Comment by Arturo254** [comment]
Good thing it wasn't the problem with the app. 
😄

**Comment by Arturo254** [comment]
Problem solved
