### ISSUE TITLE
(Enhancement) Add a share button for playlists (like Spotify or YouTube music)

### ISSUE THREAD

**Issue by Richard38907** [Arturo254/InnerTune#12]
Is it possible for you to add a button to share playlist directly from innertune?
![Screenshot_20240415-064106_InnerTune.png](https://github.com/Arturo254/InnerTune/assets/148692265/c08f3d5a-da0a-4ce5-b964-fe84b5c1b4e1)

Thank you in advance for your feedback.

**Comment by Arturo254** [comment]
If you're already logged in to YouTube Music, you can import the playlist and then share the link

Any doubts, questions or questions can be discussed here or in the telegram group 

Thank you for your feedback

**Comment by Richard38907** [comment]
Yes, but if I want to add a song to a playlist, I have to always open YouTube Music instead to make sure the song is synchronized with the account. It's possible but it's longer.

**Comment by Richard38907** [comment]
If I sync the playlist with YouTube music after adding a song from innertune, this song disappear and it restore the YouTube Music playlist state.

**Comment by Arturo254** [comment]
At the moment I think it will not be possible, because when creating the playlist a "$Private" attribute is created in the API.
and the playlist becomes private. So you can't share private playlists.
