### ISSUE TITLE
Add support localisation to albums name

### ISSUE THREAD

**Issue by Derpachi** [Arturo254/InnerTune#128]
Add album title adaptation for the selected language
![Screenshot_20240922-115636](https://github.com/user-attachments/assets/be157238-d8da-4acc-aec6-485f65ec53d8)

**Comment by Arturo254** [comment]
#### what are you talking about?

**Comment by Derpachi** [comment]
Change "liked", "offline", "my top 50" to "Понравившиеся", "Загруженные", "Мой топ 50". Because names of album similar on different languages

**Comment by Arturo254** [comment]
Could you help with the translation of opentune?

**Comment by Derpachi** [comment]
Yeah, i can

**Comment by Arturo254** [comment]
Tell me your email so I can send you the invitation

**Comment by Derpachi** [comment]
blackmy1sa@gmail.com

**Comment by Arturo254** [comment]
Thank you for your help. Do you want to be included in the contributors section?

**Comment by Derpachi** [comment]
Of course, no problem.

**Comment by Arturo254** [comment]
![image](https://github.com/user-attachments/assets/b6f336e5-f2c4-40a9-b258-cecd0262766e)
 
ready
