### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Richard38907** [Arturo254/InnerTune#13]
Add a song search option in playlists
![Screenshot (18 avr (1). 2024 20_10_09).png](https://github.com/Arturo254/InnerTune/assets/148692265/e2fb9ec7-c7cf-4597-a0ea-09d632dea88a)

**Comment by Arturo254** [comment]
# In the search bar you can search for songs among your playlists and likes.
![image](https://github.com/Arturo254/InnerTune/assets/87346871/53fceab5-020f-4dec-9fc0-f7ab124dde0f)


I'm sorry I can't answer right away. But I've had busy days.

**Comment by Richard38907** [comment]
Thank you for v 0.7.9😁! @AlessandroGalvan
