### ISSUE TITLE
Bug when play the music

### ISSUE THREAD

**Issue by jeanzinho509** [Arturo254/InnerTune#139]
When you select a song to play, it asks you to log in.
![Screenshot_20241027_132906_OpenTune](https://github.com/user-attachments/assets/7f4280b6-9df4-4ef3-89c9-460bf2e0a64f)

**Comment by jeanzinho509** [comment]
And the music isn't playing.

**Comment by Arturo254** [comment]
Just log in with your Google account

**Comment by jeanzinho509** [comment]
Since the last update, everything has been working perfectly. Good job on fixing the bugs.
