### ISSUE TITLE
Jack/Earphone Button BUG

### ISSUE THREAD

**Issue by wiskacha** [Arturo254/InnerTune#147]
En anteriores versiones la interacción del botón de los audífonos ya sea analógico o inalámbrico funcionaba correctamente para saltar a la siguiente/previa pista. En esta versión esa funcionalidad se perdió y la señal sólo pausa/reanuda la reproducción de la pista actual.

Estoy muy feliz con su trabajo y quiero agradecer por el cliente. Espero que lo puedan solventar.

— Testeado con CCA CCRA 3.5mm y 2, modelos distintos de audífonos bluetooth genéricos.

**Comment by Arturo254** [comment]
Hola que tal. Lamento los inconvenientes que estas teniendo. 
En mis dispositivos (**RedMagic 9S Pro y un Tecno Pova 5 Pro** ) no presentan ese problema. También en mis auriculares inalambricos (**Huawei FreeClip y RedMagic Cyberbuds DAO TWS**) no presentan el problema. Los gestos configurados siguen funcionando. Uno de ellos son 3 toques para pasar a la siguiente canción y si funciona.

Cualquier aclaración o problema favor de comentarlo
