### ISSUE TITLE
My favorite Artist-Albums and other things are not showing in their pods

### ISSUE THREAD

**Issue by sonisaltiner** [Arturo254/InnerTune#15]
Good afternoon. In your application, the artist, album, etc. sections that I have favorited are not displayed and it is seen that "0" is written.

Huawei MRD-LX1, android 9

![Screenshot_20240425_181750_com Arturo254 music](https://github.com/Arturo254/InnerTune/assets/132471102/ae324137-b095-4862-97f6-3de0fcd804ae)
![Screenshot_20240425_181755_com Arturo254 music](https://github.com/Arturo254/InnerTune/assets/132471102/1420c612-4ba6-48d2-80c8-ea8e64440789)
![Screenshot_20240425_181738_com Arturo254 music](https://github.com/Arturo254/InnerTune/assets/132471102/8aaefef5-c436-4f52-844a-8b0865c51c6d)
![Screenshot_20240425_181708_com Arturo254 music](https://github.com/Arturo254/InnerTune/assets/132471102/0354817d-1d1e-437a-b0ec-ba8d3f734624)

**Comment by Arturo254** [comment]
Hello, how are you doing. On my device (RedMagic 9 pro - Android 14)
If you show me the artists and playlists in my favorites 

https://github.com/Arturo254/InnerTune/assets/87346871/d46fce21-6923-49d2-ac48-d5cc8f54176f

**Comment by sonisaltiner** [comment]
Hola. Estoy bien, ¿cómo estás tú? Espero que estés teniendo un buen día. Cuando añado una canción a la lista en tu aplicación, aparece en la "Biblioteca" y en la sección "Artistas"; veo "1" en "Artista". Y sólo así puedo verla en la lista de artistas de "Mis favoritos". ¿Se trata de un error o no he entendido cómo utilizarlo?

https://github.com/Arturo254/InnerTune/assets/132471102/618a4bdd-2fc0-4207-9d60-dce31510318c

Además, parece que en un álbum faltan algunas canciones..

https://github.com/Arturo254/InnerTune/assets/132471102/862a1e3c-03d8-40a7-b444-743f05ad21b3

**Comment by Arturo254** [comment]
Hi, I hope you're having a great day Could you record a video for me? 
I don't understand very well what you're saying since I don't speak English (I speak Spanish) 
And the translator doesn't give me the right interpretation of what you mean
Thank you in advance. 😄

**Comment by sonisaltiner** [comment]
Me he puesto al día. De hecho, mi idioma es el turco, no el inglés. Gracias por su comprensión. Por cierto, puede utilizar deepl.com como traducción. 👋🏻👌🏻

**Comment by sonisaltiner** [comment]
Hola?

**Comment by Arturo254** [comment]
Hola, una disculpa por no contestar. he estado ocupado con otros proyectos pero cuentame mas sobre tu problema. por cierto Tu dispositivo es un *huawei Y6 (2019)* ?

Si es asi inenta borrar los datos de la aplicacion y descargar la version mas reciente (0.58) ,  el problema se presenta debido al firmware de huawei, si el problema persiste hagamelo saber

**Comment by Arturo254** [comment]
Hello, I have taken your problem into account and have released a new version That error should have been fixed

**Comment by Arturo254** [comment]
Hello, I have taken your problem into account and have released a new version That error should have been fixed 

Download version 0.6.0
