### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by tiago-portela** [Arturo254/InnerTune#154]
I can't download or hear any songs that I hadn't heard before. There is always a message of "unknown error", "erro desconhecido" in my language.

**Comment by Richard38907** [comment]
Log out from your yt music account. It's the only fix at the moment.

**Comment by tiago-portela** [comment]
Me not having a yt music account:

😮

**Comment by Richard38907** [comment]
Ok, are you on 1.9.1?
It works fine for me.

**Comment by tiago-portela** [comment]
Yep, 1.9.1 and no idea on how to fix this.

**Comment by Arturo254** [comment]
fixed
