### ISSUE TITLE
ERROR DESCONOCIDO - Reproducción y descargas

### ISSUE THREAD

**Issue by Sherlock-sk7** [Arturo254/InnerTune#161]
![Unknown error](https://github.com/user-attachments/assets/e567a87e-f03f-4e56-8e43-ccf62e8c277c)

**Comment by fnswjdh4782** [comment]
Mismo problema y no se soluciona :(

**Comment by Richard38907** [comment]
Temporary fix: log out from your yt-music account. It will probably be fixed on the next release.

**Comment by Arturo254** [comment]
fixed
