### ISSUE TITLE
Tarjetas 

### ISSUE THREAD

**Issue by Shidohs** [Arturo254/InnerTune#17]
Algunos tarjetas y sus bordes están fuera del margen del equipo, como tambien el texto del apartado de ajustes.

**Comment by Arturo254** [comment]
Hola. Gracias por tu comentario 

Ya está solucionado en la versión 0.6.1 
https://github.com/Arturo254/InnerTune/releases/tag/0.6.1

**Comment by Shidohs** [comment]
![Screenshot_20240606-135357_InnerTune.png](https://github.com/Arturo254/InnerTune/assets/99781106/00e19edc-2929-40da-aa73-118d1b2a94d5)

Creo no haberme explicado bien, lo siento ahí, pero me refería, a que al apartado de opciones de betas y sobre el creador esta fuera del borde, aunque no sabría que decir muy bien, ya que cuando abro la app sale eso fuera del margen, pero ahí en la foto esta dentro, será por las dimensiones de la pantalla!
