### ISSUE TITLE
Mood and genres not working

### ISSUE THREAD

**Issue by gityhubi** [Arturo254/InnerTune#22]

**Comment by Arturo254** [comment]
describe your problem

**Comment by gityhubi** [comment]
> describe your problem

https://private-user-images.githubusercontent.com/80542861/319813054-03e9f706-1e4e-4565-8c18-d0a0c3f917dd.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDk1NDksIm5iZiI6MTcxODIwOTI0OSwicGF0aCI6Ii84MDU0Mjg2MS8zMTk4MTMwNTQtMDNlOWY3MDYtMWU0ZS00NTY1LThjMTgtZDBhMGMzZjkxN2RkLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE2MjA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MjE2YjIyMDg4YTFiYzI0NDhmMDBkNTBjODc2MDhkMzY3MzI2MDhkOTU5NTcxZGQ1ZjRjMzY1OTJmYTAxZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K2Bvnwajph0TrLWpwmrHGzRLEIpTpf1ZoIzKe5nqE1E
