### ISSUE TITLE
Shortcuts issue

### ISSUE THREAD

**Issue by gityhubi** [Arturo254/InnerTune#23]
The bugs are the same as in this [fork](https://github.com/Malopieds/InnerTune)

**Comment by Arturo254** [comment]
what is the problem. Can you describe it to me and if possible, can you send me a video?

**Comment by gityhubi** [comment]
![323761220-fbba0324-222d-40b9-b8c1-e683dbb1ff40](https://github.com/Arturo254/InnerTune/assets/141925047/b606a8b0-4da9-4818-8217-0fcea2ff25fd)

**Comment by Arturo254** [comment]
Describe the problem to me

**Comment by gityhubi** [comment]
> Describe the problem to me

The shortcuts do not match the application and when you click on some of them, the application crashes

**Comment by Arturo254** [comment]
TRUE. I hadn't noticed. I will correct it as soon as possible
