### ISSUE TITLE
Pull translations from Toolate

### ISSUE THREAD

**Issue by lucasmz-dev** [Arturo254/InnerTune#24]
If it's possible, I'd be nice to pull translations from Toolate, I've recently fixed PT-BR translations for InnerTune and just found out about this fork, which I'd like to try. That work I guess kind of went down the drain with it seemingly becoming unmaintained.

**Comment by Arturo254** [comment]
Hello, I don't know "Too Late", but it would be good to know it.
It's good that you discovered this fork. The original application stopped working.

**Comment by lucasmz-dev** [comment]
Hello!
https://toolate.othing.xyz/projects/innertune/

I'm not sure if it is actually possible, could cause merging issues; It's just another instance of Weblate (which InnerTune seemed to be using)

**Comment by lucasmz-dev** [comment]
It doesn't seem like it is possible.
