### ISSUE TITLE
Liked section in home screen gone since v 0.6.3?

### ISSUE THREAD

**Issue by Richard38907** [Arturo254/InnerTune#25]
The liked button present on v 0.6.1 on the home page is gone on v 0.6.3

![Screenshot_20240612-074354_InnerTune.png](https://github.com/Arturo254/InnerTune/assets/148692265/95a25843-2ba9-4f80-a63e-9995d2e782e3)

**Comment by Arturo254** [comment]
Yes. I temporarily removed it, but I promise to add it back. I will pull out a patch
