### ISSUE TITLE
Long Press for extra Options IS Not app wide

### ISSUE THREAD

**Issue by pixelFeliks** [Arturo254/InnerTune#29]
When you search a title and have not clicked search yet there are a few results that show Up. In this Situation when you do a long click the menu doesnt pop up

**Comment by Arturo254** [comment]
I don't quite understand your point. could you record a video

**Comment by pixelFeliks** [comment]
When you search for something there are a few suggestions of what you could be looking for. in this case it is house of memories(the one with the cover art at the lower half) . I don't know if it is supposed to be like this or not. But the three dots aren't there and the long press also doesn't so anything. Can this be changed? or is this even possible?


![Screenshot_20240621-143324.png](https://github.com/Arturo254/InnerTune/assets/173176969/d37c86ae-0b58-4f38-a661-ba4f7a7a69a1)
