### ISSUE TITLE
Google Pixel Wave Design for Player

### ISSUE THREAD

**Issue by pixelFeliks** [Arturo254/InnerTune#30]
As Innertune supports Material you, I think it would be great if there was another feature by Google. On my Google Pixel the music widget has this wavy design for the playing progress. Would it be possible to integrate this as an option?

![Screenshot_20240621-144954.png](https://github.com/Arturo254/InnerTune/assets/173176969/77edbc5e-f6b8-4197-90a9-43c795153d8e)

**Comment by Arturo254** [comment]
[0.7.4](https://github.com/Arturo254/InnerTune/releases/tag/0.7.4)
