### ISSUE TITLE
⚠️YouTube API update⚠️ - pages not loading

### ISSUE THREAD

**Issue by Richard38907** [Arturo254/InnerTune#31]
When I tap on "go to album" from a title, it opens a blank page

I send you the bug report

-![bugreport-CPH2415EEA-UKQ1.230924.001-2024-06-21-20-47-39.zip](https://github.com/user-attachments/files/15931979/bugreport-CPH2415EEA-UKQ1.230924.001-2024-06-21-20-47-39.zip)

![bugreport-CPH2415EEA-UKQ1.230924.001-2024-06-21-20-47-39-dumpstate_log-14731.txt](https://github.com/user-attachments/files/15931981/bugreport-CPH2415EEA-UKQ1.230924.001-2024-06-21-20-47-39-dumpstate_log-14731.txt)

![dumpstate-stats.txt](https://github.com/user-attachments/files/15931980/dumpstate-stats.txt)

**Comment by Richard38907** [comment]
Bug also present on YouTube music playlists. Impossible to load them anymore.

**Comment by Richard38907** [comment]
Bug present on my two phones with android 13 and 14

**Comment by Richard38907** [comment]
Bug present on all yt music streaming apps since yesterday.

**Comment by Richard38907** [comment]
![Gmail - Re_ [z-huang_InnerTune] Import not working (Issue #1295).pdf](https://github.com/user-attachments/files/15937547/Gmail.-.Re_.z-huang_InnerTune.Import.not.working.Issue.1295.pdf)

YouTube changed his API.

**Comment by Arturo254** [comment]
solved

**Comment by sonisaltiner** [comment]
Still the problem persists(?)

https://github.com/Arturo254/InnerTune/assets/132471102/c094ff75-f371-43a9-b3f4-8a865bc1eb09

https://github.com/Arturo254/InnerTune/assets/132471102/2a7e90e3-b4f0-40ac-844b-d18d08f69159
