### ISSUE TITLE
Malware(?)

### ISSUE THREAD

**Issue by sonisaltiner** [Arturo254/InnerTune#33]
Hola, buenas tardes hermano. La aplicación "Optimización" compatible con Avast en mi teléfono ha encontrado un virus malicioso. Cuando escaneo el archivo apk a virustotal.com, viene limpio de todas las exploraciones?

![Screenshot_20240625_163757_com huawei systemmanager](https://github.com/Arturo254/InnerTune/assets/132471102/f695660a-657e-43f5-9315-3287f14d7d34)

https://github.com/Arturo254/InnerTune/assets/132471102/3c1ae3d0-9ea4-45f4-a7c5-dbb2cbf255be

**Comment by AlexIhmisviha** [comment]
Avast itself is malware, uninstall that garbage.

**Comment by Arturo254** [comment]
This error occurs because the application signature is not associated with that of Google Play

**Comment by assier08** [comment]
The app is open source, if there was malware, the code will change to eliminate the malware
