### ISSUE TITLE
Falla en la versión 

### ISSUE THREAD

**Issue by Thanos1567** [Arturo254/InnerTune#39]
No se puede ver a los artistas ni los albunes me aparece en blanco 
![Screenshot_20240704_002235](https://github.com/Arturo254/InnerTune/assets/174684303/621484c6-c587-4db4-8f58-5cca26691e6e)
![Screenshot_20240704_002224](https://github.com/Arturo254/InnerTune/assets/174684303/fb700a41-fc98-413c-a555-d5f41f6560d3)

**Comment by Arturo254** [comment]
gracias por tu reporte . estoy tratando de solucionar todos los errores
