### ISSUE TITLE
Why didn't you merge my pull request? Were there issues?

### ISSUE THREAD

**Issue by AlessandroGalvan** [Arturo254/InnerTune#49]

**Comment by Arturo254** [comment]
update the code to the new version to be able to merge

**Comment by AlessandroGalvan** [comment]
> update the code to the new version to be able to merge 

- again?? Really??? Couldn't you merge it when the version was the same? For fuck's sake I'm contributing to the project but i see no interest from your end. I'll see if i have time to update the code, if not just copy and paste the code

**Comment by Arturo254** [comment]
You must understand that with each version there is a code change and it must be updated to multiplatform Kotlin. so don't complain to me. because the problem is not mine
