### ISSUE TITLE
la app se cierra 

### ISSUE THREAD

**Issue by Isav08** [Arturo254/InnerTune#50]
al presionar el botón indicado en la imagen la aplicación se cierra.
![IMG_20240713_050341](https://github.com/user-attachments/assets/db3e2b3e-745e-42ef-ba3a-919344a99fa0)
![Screenshot_20240713-050102](https://github.com/user-attachments/assets/43e58be6-051a-4402-8108-161d909c6a6e)

**Comment by Isav08** [comment]
También al presionar esta zona la app se cierra.
![IMG_20240713_051951](https://github.com/user-attachments/assets/53413da3-c132-4f28-911a-e21dc4c7e74d)

**Comment by Arturo254** [comment]
Solucionado. Puedes descargar ya la 0.7.3 (pre release) 😄

**Comment by Isav08** [comment]
> Solucionado. Puedes descargar ya la 0.7.3 (pre release) 😄

En la version 0.7.3 sigo teniendo los mismos problemas.

**Comment by Isav08** [comment]
El problema de la primera imagen solo se presenta en offline, liked y my top 50. En las playlists hechas por mí no.

**Comment by Arturo254** [comment]
Solucionado en la versión 0.7 4

Gracias por tu comentario 💗

**Comment by Isav08** [comment]
> Solucionado en la versión 0.7 4
> 
> Gracias por tu comentario 💗

Funciona perfecto. 
El problema en el caso de ajuste donde se encuentran la tarjetas al presionar sobre ellas la app se sigue cerrando.

**Comment by Arturo254** [comment]
> > Solucionado en la versión 0.7 4
> > Gracias por tu comentario 💗
> 
> Funciona perfecto. El problema en el caso de ajuste donde se encuentran las tarjetas al presionar sobre ellas la app se sigue cerrando.



A mi no me sucede ese problema

**Comment by Arturo254** [comment]
puedes ponerte directamente en contacto conmigo mediante whatsapp

**Comment by Isav08** [comment]
> > > Solucionado en la versión 0.7 4
> > > Gracias por tu comentario 💗
> > 
> > 
> > Funciona perfecto. El problema en el caso de ajuste donde se encuentran las tarjetas al presionar sobre ellas la app se sigue cerrando.
> 
> A mi no me sucede ese problema

El problema no es todo el tiempo, en algunas ocasiones al presionar cambia de tarjeta pero en otras simplemente se cierra la app.
Pero incluso cuando se puede cambiar de tarjeta si lo haces rápidamente se cierra la app.

**Comment by Isav08** [comment]
Otro punto es que en ocasiones al entrar en el apartado de ajustes se elentece la app, pero si en el apartado de tarjetas esta en blanco fluye sin problemas.

**Comment by Isav08** [comment]
Acabo de entrar en la app y me percaté de que cuando la tarjeta es de color y cambia a otra de color no se cierra la app, pero siempre que se encuentra en blanco y presiono para cambiar de tarjeta se cierra:
![Screenshot_20240715-221811](https://github.com/user-attachments/assets/e0454b01-9f90-4051-8311-b5427fd0cb8d)
![Screenshot_20240715-221903](https://github.com/user-attachments/assets/7f7df647-8cf2-4a22-8982-0867abf14154)

**Comment by Arturo254** [comment]
que android tienes?

**Comment by Arturo254** [comment]
https://github.com/user-attachments/assets/c069d2d1-7dcd-4d50-a4b4-7b2f6ea6323b

**Comment by Isav08** [comment]
> que android tienes?

android 7.0

**Comment by Arturo254** [comment]
> > que android tienes?
> 
> android 7.0

Yo digo que ha de ser problema de tu dispositivo. Por la versión de android. Pero de todas formas tratare de arreglarlo

**Comment by Isav08** [comment]
> > > que android tienes?
> > 
> > 
> > android 7.0
> 
> Yo digo que ha de ser problema de tu dispositivo. Por la versión de android. Pero de todas formas tratare de arreglarlo

Entiendo, gracias.
