### ISSUE TITLE
Please add a wavy bar.

### ISSUE THREAD

**Issue by AJTechOfficial** [Arturo254/InnerTune#53]
Please add a way sound bar like this in this innertune fork
![Screenshot_2024-07-15-18-50-39-44_56635af9b6ad4512d4187a5a49185a25](https://github.com/user-attachments/assets/caad56d6-56b1-416f-a720-69b25463c417)
Link of the fork which contains this feature:
https://github.com/Malopieds/InnerTune/tree/v0.5.8

Thanks.

**Comment by Arturo254** [comment]
In fact I implemented it first, you can download version 0.7.3 (pre release)

**Comment by AJTechOfficial** [comment]
> In fact I implemented it first, you can download version 0.7.3 (pre release)

oh my bad

**Comment by AJTechOfficial** [comment]
implemented already (I'm an idiot)
