### ISSUE TITLE
SUGGESTION

### ISSUE THREAD

**Issue by AJTechOfficial** [Arturo254/InnerTune#56]
Please add a way to get custom playlist icons,like in YouTube music changing the icon is available, but in InnerTune it's just a mix of first 4 songs.
![Screenshot_2024-07-16-17-24-21-98_a1ef93026ea01fb6aceba355d00a73a0](https://github.com/user-attachments/assets/e8aff87b-a1cc-4971-8da6-d163cff225e0)

In Innertune:
![Screenshot_2024-07-16-17-24-45-83_e6138d569585a36f237f402ac470e477](https://github.com/user-attachments/assets/042c580d-ad58-4de0-bff1-d5a3bac3c4bf)

Thanks.

**Comment by AJTechOfficial** [comment]
@Arturo254

**Comment by AlessandroGalvan** [comment]
done, it should be in the next update 😄

**Comment by AJTechOfficial** [comment]
The suggestion has been implemented, go in the playlist and click on the Playlist icon and press the pencil option.
