### ISSUE TITLE
merge

### ISSUE THREAD

**Issue by AlessandroGalvan** [Arturo254/InnerTune#57]
I updated the pull request, now merge it please

**Comment by Arturo254** [comment]
listo

**Comment by Richard38907** [comment]
Unfortunately, there is a glitch: #78

**Comment by Arturo254** [comment]
> I updated the pull request, now merge it please

Are you going to fix the problem? If not, you will fix it to remove the fusion

**Comment by Richard38907** [comment]
@AlessandroGalvan We love your feature because it's useful. Please provide us a fix.
Thank you in advance🙏

**Comment by AlessandroGalvan** [comment]
> @AlessandroGalvan We love your feature because it's useful. Please provide us a fix.
> Thank you in advance🙏

I already know about this issue, I was on vacation so i couldn't fix it. Give me a couple of days and i will fix it

**Comment by Richard38907** [comment]
Thank you for your reply. I hope you had a good vacation🌴!
