### ISSUE TITLE
Crash when typing % in search bar

### ISSUE THREAD

**Issue by Richard38907** [Arturo254/InnerTune#7]
Try to search a song that contains "%" in the title and the app crashes.(Bug present on the original release too.)

![Screenshot_20240411-134342.png](https://github.com/Arturo254/InnerTune/assets/148692265/b681efe0-88cc-4406-abd8-a0d413684a7a)

**Comment by Arturo254** [comment]
The "%" symbol takes it as a variable, since I used it to search for songs using the YouTube Music API. And also use it to be able to specify the name of the song to download

**Comment by Richard38907** [comment]
Okay I understand. Will you provide a fix for it?

**Comment by Arturo254** [comment]
At the moment there is no solution, it is a difficult problem to solve since the API includes that sign and I cannot remove it since it would break everything

**Comment by Richard38907** [comment]
Okay thank you for your answer🙂. (I tested it on, ViMusic RiMusic and HarmonMusic and they don't have the problem.)
