### ISSUE TITLE
3 versions numbers for the same version😱

### ISSUE THREAD

**Issue by Richard38907** [Arturo254/InnerTune#71]
https://github.com/user-attachments/assets/103aec98-b7ae-4a3d-91cf-c68dbdf03270

v 0.8.0 is 0.7.8 stable and 0.7.9 beta.

What s the correct one?

**Comment by Richard38907** [comment]
Related issue #67

**Comment by Arturo254** [comment]
It's just a bug that doesn't affect anything, but the bug is now fixed. #67

**Comment by Richard38907** [comment]
Yeah it' s a minor bug. But it is weird. Thank you for the fix.
