### ISSUE TITLE
Enhancement- Auto close keyboard on a song search in playlists

### ISSUE THREAD

**Issue by Richard38907** [Arturo254/InnerTune#73]
When you hit the search button on the keyboard, I would like this one to be closed
![Screenshot_20240728-093702.png](https://github.com/user-attachments/assets/c59533c0-e322-499e-985b-f11a00623b60)

In Spotify, it does that right

https://github.com/user-attachments/assets/bd841d5e-be17-4e1b-b8c3-8bf91a19b5f1

It will be nice, thank you in advance

**Comment by AlessandroGalvan** [comment]
done 😄

**Comment by Richard38907** [comment]
Thank you for the patch🎉. I just noticed another annoying thing also present on previous versions: 

1) Search a song with the search bar
2) Play the song (optional)
3) Exit the app with the home button/gesture(don't kill it)
4) Go back to the app again
➡️See the error: **The keyboard auto opens because it didn't leave the search bar.**

See in video

https://github.com/user-attachments/assets/609e1a7e-41db-4a75-8b47-77546ee80b1f

**Comment by Richard38907** [comment]
Thank you for the patch🎉. I just noticed another annoying thing also present on previous versions: 

1) Search a song with the search bar
2) Play the song (optional)
3) Exit the app with the home button/gesture(don't kill it)
4) Go back to the app again
➡️See the error: **The keyboard auto opens because it didn't leave the search bar even if you hit the new ❌button.**

See in video

https://github.com/user-attachments/assets/609e1a7e-41db-4a75-8b47-77546ee80b1f

**Comment by Richard38907** [comment]
What's the problem @Arturo254 ?

**Comment by AlessandroGalvan** [comment]
> Thank you for the patch🎉. I just noticed another annoying thing also present on previous versions: 
> 
> 1) Search a song with the search bar
> 2) Play the song (optional)
> 3) Exit the app with the home button/gesture(don't kill it)
> 4) Go back to the app again
> ➡️See the error: **The keyboard auto opens because it didn't leave the search bar even if you hit the new ❌button.**
> 
> See in video
> 
> https://github.com/user-attachments/assets/609e1a7e-41db-4a75-8b47-77546ee80b1f
> 
> 

@Richard38907 thanks for the report. I'll work on it, I think in version 0.8.7 it'll be fixed.

**Comment by Richard38907** [comment]
You are my life saver🔥!
