### ISSUE TITLE
problem with the search bar in playlists 

### ISSUE THREAD

**Issue by WHONEYR** [Arturo254/InnerTune#78]
currently in version 0.8.4Stable there is a bug where, every time you search for a song in one of your playlists using the search bar, and select the song you want, another song appears in the place you searched for, following the order of the playlist. , here is an example video: https://github.com/user-attachments/assets/85bce8b8-f527-4c42-8401-21b8d21a7f65

**Comment by Richard38907** [comment]
Same here on 0.8.4. Please fix this glitch.

This bug only happens on imported and local playlists.

**Comment by AlessandroGalvan** [comment]
fixed 😄

**Comment by Richard38907** [comment]
What is the problem @Arturo254 🤔?
