### ISSUE TITLE
Rebrand Request

### ISSUE THREAD

**Issue by z-huang** [Arturo254/InnerTune#79]
Hi, I am the original author of InnerTune (https://github.com/z-huang/InnerTune).

I would like to ask you to change the name of your forked app. Using the same name as mine can cause confusion among users about the differences between each fork. I have already had users ask me which one is the original InnerTune. Using a name that reflects your own style will make it easier for users to remember your app. Additionally, I hope you can design your own icon to better express your style. I hope you will consider my request. Thank you!

**Comment by Arturo254** [comment]
Hi. You're my idol haha.
I don't know if you mind if I leave the same name and icon for the application. Both the name and the icon seem perfect to me and fit the application.
I really would like to keep it, but tell me

a question. Can I put your username in the contributions section?

**Comment by z-huang** [comment]
My concern is that users may be confused about which one is the "real" app. In fact, as time goes on, the forks of InnerTune will have many differences compared to the original InnerTune app. Therefore, I think the forks can get their own name and icon to gain their own recognition. Also, your version code (0.8.4) is much higher than my version (0.5.4). Users may think yours being newer, while it can't be compared this way.

See https://github.com/Malopieds/InnerTune/issues/212, where people are considering giving @Malopieds 's fork a new identity.

> Can I put your username in the contributions section?

Sure!

**Comment by Arturo254** [comment]
ok just give me time to think of a new name and icon (i'm not very good at that)

**Comment by z-huang** [comment]
You can create an issue and let the community provide ideas, just like https://github.com/z-huang/InnerTune/issues/35 and https://github.com/z-huang/InnerTune/issues/305.

**Comment by Arturo254** [comment]
could you steal this from me?
https://github.com/z-huang/InnerTune/issues/305#issuecomment-1570171296

**Comment by JPGuillemin** [comment]
Hi

I think Opentune would be a great name.

I have ideas for icons and can provide svg files

All the best
Jp

**Comment by Arturo254** [comment]
> Hi
> 
> I think Opentune would be a great name.
> 
> I have ideas for icons and can provide svg files
> 
> All the best
> Jp

Hi JP. It's a great name. Thanks for your input. If you'd like, you can contribute by designing the icon. 😉

**Comment by JPGuillemin** [comment]
> > Hi
> > I think Opentune would be a great name.
> > I have ideas for icons and can provide svg files
> > All the best
> > Jp
> 
> Hi JP. It's a great name. Thanks for your input. If you'd like, you can contribute by designing the icon. 😉

Ok. I'm back from holidays next WE, I will build the icon and send it to you hopefully sunday.

Jp

**Comment by JPGuillemin** [comment]
I found some time to do it.

Do you like it  ?

The PNG :
![Opentune](https://github.com/user-attachments/assets/51da6441-72f8-43fd-9ac9-5438975f2b31)

**Comment by JPGuillemin** [comment]
The SVG
![Opentune](https://github.com/user-attachments/assets/977ec393-15f4-480d-8624-e42fc2a9d8c4)

**Comment by Arturo254** [comment]
> I found some time to do it.
> 
> Do you like it ?
> 
> The PNG : ![Opentune](https://private-user-images.githubusercontent.com/55490396/357705605-51da6441-72f8-43fd-9ac9-5438975f2b31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTU4NTEsIm5iZiI6MTcyMzY5NTU1MSwicGF0aCI6Ii81NTQ5MDM5Ni8zNTc3MDU2MDUtNTFkYTY0NDEtNzJmOC00M2ZkLTlhYzktNTQzODk3NWYyYjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA0MTkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNjFlNzNiOWY4MzkzOTdmZTU3YzQ0YmNkZDRlYzMzZDY0NWJmZTFkNmY5NjI2YWNjOTkyZjM4MWEwNmE2ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g2lqnzPXLTM2fJIJ4_k-SU85UqDSHQ0Bx767LBQWUk8)

Could it be something more modern, minimalist and beautiful?

**Comment by Arturo254** [comment]
Do you think we can communicate via WhatsApp or Telegram?

**Comment by JPGuillemin** [comment]
Telegram, yes

**Comment by JPGuillemin** [comment]
This icon is minimalist, modern, and I find it very nice. 

An icon doesnt have to be "beautiful, it has to be self-meaningful, unique, easily identifiable. 

Please point me to existing icons that you like for the style.

**Comment by Arturo254** [comment]
> Telegram, yes

This is my username:
https://t.me/ArturoCervantes254

**Comment by Arturo254** [comment]
> This icon is minimalist, modern, and I find it very nice.
> 
> An icon doesnt have to be "beautiful, it has to be self-meaningful, unique, easily identifiable.
> 
> Please point me to existing icons that you like for the style.

mm I don't know. Something more modern. In my opinion that icon looks like it's from 2010 haha

**Comment by JPGuillemin** [comment]
> > This icon is minimalist, modern, and I find it very nice.
> > An icon doesnt have to be "beautiful, it has to be self-meaningful, unique, easily identifiable.
> > Please point me to existing icons that you like for the style.
> 
> mm I don't know. Something more modern. In my opinion that icon looks like it's from 2010 haha

OK :) I respect your taste. Let's discuss about another style :)

**Comment by JPGuillemin** [comment]
![opentune4](https://github.com/user-attachments/assets/00c7ff86-9d58-42d8-a0d1-1359c7887dd9)

**Comment by Malopieds** [comment]
Hey @Arturo254, I see you're not using the above logo. If @JPGuillemin agrees, could I use it for my fork?
Thanks in advance.

**Comment by Arturo254** [comment]
> Hey @Arturo254, I see you're not using the above logo. If @JPGuillemin agrees, could I use it for my fork? Thanks in advance.

Hi. How are you?
Sure. I don't use it anymore. It's a very nice icon and would look good with your app.

**Comment by JPGuillemin** [comment]
> Hey @Arturo254, I see you're not using the above logo. If @JPGuillemin agrees, could I use it for my fork? Thanks in advance.

Of course :) you're welcome !
