### ISSUE TITLE
Blur option does not work properly

### ISSUE THREAD

**Issue by CodyLax** [Arturo254/InnerTune#80]
The blur option doesn't work on my device, it doesn't completely blur the background, I don't know if it's because my phone doesn't support blur, but even so if you could correct it, I'd be happy if you could tell me something about this bug.

https://github.com/user-attachments/assets/7ae1cdad-a260-4a17-8fe9-78f03ec3ba41

**Comment by Arturo254** [comment]
What version of Android do you have?

**Comment by ghost** [comment]
> What version of Android do you have?

Android 10
