### ISSUE TITLE
Bug - Radio queue not working

### ISSUE THREAD

**Issue by Richard38907** [Arturo254/InnerTune#85]
Probably due to a YouTube API change, "start radio" is not working. It only plays the first song and provides an empty queue.

![Screenshot_20240809-130735_InnerTune.png](https://github.com/user-attachments/assets/b8d1a177-75bb-4f5c-8541-7653f6317467)

![Screenshot_20240809-130740_InnerTune.png](https://github.com/user-attachments/assets/35c4b512-a8cb-42d2-8da9-caa2f58b2de2)

**Comment by Arturo254** [comment]
Solved
