### ISSUE TITLE
Thumbnail Size is Not Full

### ISSUE THREAD

**Issue by zenzer0s** [Arturo254/InnerTune#89]
I found a bug where thumbnail of video songs is not full as in YouTube and YouTube music 
![Screenshot_20240811-152848](https://github.com/user-attachments/assets/e90d6d0a-cf54-40ec-aa01-d5e457c8c642)
![Screenshot_20240811-152837](https://github.com/user-attachments/assets/9a21bb22-3976-4cc3-b42c-e70f863250a5)

Compare these

**Comment by Arturo254** [comment]
It's not a bug. That's what I did, because the song covers are not the same size as the video covers.

What player is the second one?

**Comment by zenzer0s** [comment]
It's blackhole
